name: sample workflow 

on: push 

jobs: 

  sample:
    runs-on: ubuntu-latest
    steps:
      - name: runnig some commands
        run: |
          pwd
          ls
          whoami
          df -h
