name: sample workflow 

on: push

jobs: 

  sample:
    runs-on: ubuntu-latest
    steps:
      - name: checkout loacl code
        uses: actions/checkout@v3
        
      - name: building pushing docker images
        run: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASS }}

          docker build -t pythonappnew:1.0 .

          docker tag pythonappnew:1.0 dockertry1729/pythonappnew:1.0 

          docker push dockertry1729/pythonappnew:1.0



